# Generated by Django 4.0.5 on 2022-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Water authority', 'Water authority'), ('KSEB', 'KSEB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Work in progress', 'Work in progress'), ('Work Done', 'Work Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True),
        ),
    ]
