# Generated by Django 4.0.5 on 2022-06-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0012_mechanic_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='work_category',
            field=models.CharField(choices=[('KSEB', 'KSEB'), ('Other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Mechanic2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/MechanicProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=500, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('work_category', models.CharField(choices=[('WATER AUTHORITY', 'WATER AUTHORITY'), ('Other', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
